### ISSUE TITLE
Bài tập đầu tiên môn Lập trình Front-End. Phối màu trang web

### ISSUE THREAD

**Issue by ngonghia19092000** [ngonghia19092000/Front-End-2021#1]
Yêu cầu: Nhóm chọn ra 1 template web có sẳn thực hiện phối màu trang web.Mỗi thành viên sẽ tạo ra 2 version màu mới khác  màu với mẫu đã cho.
Phân chia công việc:
 - Phạm Thế Bảo sẽ làm và đặt tên phần việc của mình làm với tên thư mục là V1 và V2
 - Nguyễn Đăng Dụng sẽ làm và đặt tên phần việccủa mình làm với tên thư mục là V3 và V4
 - Ngô Minh Nghĩa sẽ làm và đặt tên phần việccủa mình làm với tên thư mục là V5 và V6
Hạn cuối làm bài là 23h00 28/3/2021.

**Comment by 18130016** [comment]
Đã làm xong V1&V2
